<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "templates".
 *
 * @property int $id
 * @property string $title
 * @property string $filename
 * @property int $created_at
 * @property int $updated_at
 *
 * @property string $template
 */
class Templates extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'templates';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at', 'updated_at'], 'integer'],
            [['title', 'filename'], 'string', 'max' => 255],
            [['title'], 'unique'],
            [['filename'], 'unique'],
            [['created_at', 'updated_at'], 'default', 'value' => time()],
            [['title', 'filename', 'created_at', 'updated_at'], 'required'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'template' => 'Template',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    public function beforeSave($insert)
    {

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     * @return TemplatesQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TemplatesQuery(get_called_class());
    }

    public function getTemplate()
    {
        $path = Yii::getAlias("@templates/$this->filename");
        return file_exists($path) ? file_get_contents($path) : null;
    }

    public function setTemplate(string $template)
    {
        $path = Yii::getAlias("@templates/$this->filename");
        $file = fopen($path, 'w');
        fwrite($file, $template);
        fclose($file);
    }
}
